---
services:
  ## Mongo Docker Compose Config
  mongo:
    container_name: mongo
    image: mongo:8.2.2-noble
    # restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./databases/mongo-data:/data/db
    profiles:
      - infrastructure

  postgres-order:
    container_name: postgres-order
    image: postgres:15.15-trixie
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./databases/postgres-order:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    # restart: always
    profiles:
      - infrastructure

  postgres-stock-check:
    container_name: postgres-stock-check
    image: postgres:15.15-trixie
    environment:
      POSTGRES_DB: stock_check_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./databases/postgres-stock-check:/data/postgres
    ports:
      - "5432:5432"
    # restart: always
    profiles:
      - infrastructure

  postgres-author:
    container_name: postgres-author
    image: postgres:15.15-trixie
    environment:
      POSTGRES_DB: author_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./databases/postgres-author:/data/postgres
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    # restart: always
    profiles:
      - infrastructure

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.5
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    profiles:
      - infrastructure

  broker:
    image: confluentinc/cp-kafka:7.9.5
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    profiles:
      - infrastructure

  ## Zipkin
  zipkin:
    image: openzipkin/zipkin:3-amd64
    container_name: zipkin
    ports:
      - "9411:9411"
    profiles:
      - infrastructure

  ## Eureka Server
  discovery-server:
    image: microservices-bookstore/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    profiles:
      - discovery-config

  ## Config Server
  config-server:
    image: microservices-bookstore/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - discovery-server
    profiles:
      - discovery-config

  api-gateway:
    image: microservices-bookstore/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    profiles:
      - services

  ## Book Service Docker Compose Config
  book-service:
    container_name: book-service
    image: microservices-bookstore/book-service:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - api-gateway
    profiles:
      - services

  ## Author Service Docker Compose Config
  author-service:
    container_name: author-service
    image: microservices-bookstore/author-service:latest
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - api-gateway
    profiles:
      - services

  ## Order Service Docker Compose Config
  order-service:
    container_name: order-service
    image: microservices-bookstore/order-service:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - api-gateway
    profiles:
      - services

  ## Stock Check Service Docker Compose Config
  stock-check-service:
    container_name: stock-check-service
    image: microservices-bookstore/stock-check-service:latest
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - api-gateway
    profiles:
      - services

  ## Message Service Docker Compose Config
  message-service:
    container_name: message-service
    image: microservices-bookstore/message-service:latest
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - api-gateway
    profiles:
      - services

  ## Prometheus
  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    # restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - book-service
      - stock-check-service
      - order-service
      - message-service
    profiles:
      - services

  ## Grafana
  grafana:
    image: grafana/grafana-oss:12.2.0-17142428006
    container_name: grafana
    # restart: always
    ports:
      - "3001:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    profiles:
      - services

  ## NextJS Frontend
  nextjs-frontend:
    container_name: nextjs-frontend
    image: microservices-bookstore/nextjs-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    profiles:
      - services

  ## DB Admin Tools
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.8.0
    environment:
      # Web Interface Credentials
      PGADMIN_DEFAULT_EMAIL: admin@bookstore.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./databases/pgadmin-data:/var/lib/pgadmin
      - ./dbadmin/pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres-order
      - postgres-stock-check
      - postgres-author
    ports:
      - "5050:80"
    profiles:
      - extra-dbadmin

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0-20-alpine3.19
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      # Connection details for the 'mongo' service
      ME_CONFIG_MONGODB_SERVER: mongo
      # Mongo is running without authentication in your setup, so no credentials needed.
    depends_on:
      - mongo
    profiles:
      - extra-dbadmin
